STDOUT:
Using MongoDB connection: mongodb+srv://materaccount:*****@discovr.vzlnmqb.mongodb.net/?retryWrites=true&w=majority&appName=Discovr
Connecting to MongoDB...
Disconnected from MongoDB


STDERR:
Error checking Fortune events: MongoServerError: bad auth : Authentication failed.
    at Connection.sendCommand (/Users/seongwoohan/CascadeProjects/discovr-api-server/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:299:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Connection.command (/Users/seongwoohan/CascadeProjects/discovr-api-server/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:327:26)
    at async executeScram (/Users/seongwoohan/CascadeProjects/discovr-api-server/node_modules/mongoose/node_modules/mongodb/lib/cmap/auth/scram.js:79:22)
    at async ScramSHA256.auth (/Users/seongwoohan/CascadeProjects/discovr-api-server/node_modules/mongoose/node_modules/mongodb/lib/cmap/auth/scram.js:39:16)
    at async performInitialHandshake (/Users/seongwoohan/CascadeProjects/discovr-api-server/node_modules/mongoose/node_modules/mongodb/lib/cmap/connect.js:104:13)
    at async connect (/Users/seongwoohan/CascadeProjects/discovr-api-server/node_modules/mongoose/node_modules/mongodb/lib/cmap/connect.js:24:9) {
  errorLabelSet: Set(2) { 'HandshakeError', 'ResetPool' },
  errorResponse: {
    ok: 0,
    errmsg: 'bad auth : Authentication failed.',
    code: 8000,
    codeName: 'AtlasError'
  },
  ok: 0,
  code: 8000,
  codeName: 'AtlasError',
  connectionGeneration: 0
}
